export { default as Home } from './Home/Home'
export { default as Missions } from './Missions/Missions'
export { default as Projets } from './Projets/Projets'
export { default as Collectif } from './Collectif/Collectif'
export { default as Contact } from './Contact/Contact'
export { default as SingleProjectPage } from './SingleProjectPage/SingleProjectPage'