export { default as Header } from './Header/Header'
export { default as Menu } from './Menu/Menu'
export { default as Projet } from './Projet/Projet'
export { default as ScrollToTop } from './ScrollToTop/ScrollToTop'
export { default as Friends } from './Friends/Friends'
export { default as Carousel } from './Carousel/Carousel'
export { default as Mission } from './Mission/Mission'